### ISSUE TITLE
Do you think you could update this to the latest version? react-redux-firebase has gone through some major changes and it would help a lot!

### ISSUE THREAD

**Issue by kartikgupta1072** [clairechabas/firebase-auth-react-redux#1]

**Comment by clairechabas** [comment]
Thanks for the request, I'll work on it and let you know when I release an updated version :)

**Comment by kartikgupta1072** [comment]
Thank you!

**Comment by clairechabas** [comment]
I know this is from a long time ago but just for sake of it: I stopped maintaining this repo which was too out of date on all fronts, I created a new one recently for anyone looking to set up auth with Firebase in a React app using Next.js: https://github.com/clairechabas/auth-firebase-next-react-jotai
